import 'package:clipsync_core/src/model/clip_content_type.dart';
import 'package:meta/meta.dart';

/// One clipboard entry as stored locally and in every backend.
///
/// [toMap] / [ClipItem.fromMap] define the canonical snake_case document
/// shape; each backend adapter converts between this map and its native
/// structure (SQL row, JSON document, BSON document, Firestore fields).
///
/// Timestamps are always UTC. `deletedAt != null` marks a tombstone; items are
/// never physically deleted by the sync engine so every device converges.
@immutable
class ClipItem {
  /// Creates an item. Prefer [ClipItem.create] for new local captures.
  const ClipItem({
    required this.id,
    required this.deviceId,
    required this.deviceName,
    required this.type,
    required this.content,
    required this.contentHash,
    required this.sizeBytes,
    required this.createdAt,
    required this.updatedAt,
    this.blobRef,
    this.encrypted = false,
    this.nonce,
    this.deletedAt,
  });

  /// Builds a fresh, unencrypted item captured on this device.
  factory ClipItem.create({
    required String id,
    required String deviceId,
    required String deviceName,
    required ClipContentType type,
    required String content,
    required String contentHash,
    required int sizeBytes,
    required DateTime now,
    String? blobRef,
  }) {
    final ts = now.toUtc();
    return ClipItem(
      id: id,
      deviceId: deviceId,
      deviceName: deviceName,
      type: type,
      content: content,
      contentHash: contentHash,
      sizeBytes: sizeBytes,
      blobRef: blobRef,
      createdAt: ts,
      updatedAt: ts,
    );
  }

  /// Parses the canonical map produced by [toMap].
  ///
  /// Tolerates timestamps as ISO-8601 strings, [DateTime] instances or epoch
  /// milliseconds so backends can hand over their native representation.
  factory ClipItem.fromMap(Map<String, Object?> map) => ClipItem(
    id: map['id']! as String,
    deviceId: (map['device_id'] ?? '') as String,
    deviceName: (map['device_name'] ?? '') as String,
    type: ClipContentType.fromWire(map['content_type'] as String?),
    content: (map['content'] ?? '') as String,
    blobRef: map['blob_ref'] as String?,
    contentHash: (map['content_hash'] ?? '') as String,
    sizeBytes: _toInt(map['size_bytes']),
    encrypted: (map['encrypted'] ?? false) == true,
    nonce: map['nonce'] as String?,
    createdAt: parseTimestamp(map['created_at'])!,
    updatedAt: parseTimestamp(map['updated_at'])!,
    deletedAt: parseTimestamp(map['deleted_at']),
  );

  /// Stable UUID v4, generated by the capturing device.
  final String id;

  /// Device that captured the item.
  final String deviceId;

  /// Human-readable device name at capture time.
  final String deviceName;

  /// Payload kind.
  final ClipContentType type;

  /// Text, or base64 for binary types, or ciphertext when [encrypted].
  final String content;

  /// Backend-specific reference (storage path, attachment name) for large
  /// binaries that were not inlined in [content].
  final String? blobRef;

  /// SHA-256 hex of the plaintext payload; used for de-duplication.
  final String contentHash;

  /// Size of the plaintext payload in bytes.
  final int sizeBytes;

  /// Whether [content] is an AES-GCM ciphertext (see `ClipCipher`).
  final bool encrypted;

  /// Base64 AES-GCM nonce when [encrypted].
  final String? nonce;

  /// Capture time (UTC).
  final DateTime createdAt;

  /// Last modification time (UTC); drives the sync cursor.
  final DateTime updatedAt;

  /// Tombstone time (UTC) or `null` when live.
  final DateTime? deletedAt;

  /// Whether this item is a tombstone.
  bool get isDeleted => deletedAt != null;

  /// Canonical document shape shared by all backends.
  Map<String, Object?> toMap() => <String, Object?>{
    'id': id,
    'device_id': deviceId,
    'device_name': deviceName,
    'content_type': type.wire,
    'content': content,
    'blob_ref': blobRef,
    'content_hash': contentHash,
    'size_bytes': sizeBytes,
    'encrypted': encrypted,
    'nonce': nonce,
    'created_at': createdAt.toUtc().toIso8601String(),
    'updated_at': updatedAt.toUtc().toIso8601String(),
    'deleted_at': deletedAt?.toUtc().toIso8601String(),
  };

  /// Returns a copy with the given fields replaced.
  ClipItem copyWith({
    String? content,
    String? blobRef,
    bool? encrypted,
    String? nonce,
    DateTime? updatedAt,
    DateTime? deletedAt,
    bool clearNonce = false,
    bool clearDeletedAt = false,
  }) => ClipItem(
    id: id,
    deviceId: deviceId,
    deviceName: deviceName,
    type: type,
    content: content ?? this.content,
    blobRef: blobRef ?? this.blobRef,
    contentHash: contentHash,
    sizeBytes: sizeBytes,
    encrypted: encrypted ?? this.encrypted,
    nonce: clearNonce ? null : (nonce ?? this.nonce),
    createdAt: createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    deletedAt: clearDeletedAt ? null : (deletedAt ?? this.deletedAt),
  );

  /// Marks the item as deleted at [now] and drops the payload so the
  /// backend no longer stores it.
  ClipItem tombstone(DateTime now) => copyWith(
    content: '',
    deletedAt: now.toUtc(),
    updatedAt: now.toUtc(),
  );

  /// Parses a timestamp in any of the representations backends produce.
  static DateTime? parseTimestamp(Object? value) => switch (value) {
    null => null,
    final DateTime d => d.toUtc(),
    final String s when s.isEmpty => null,
    final String s => DateTime.parse(s).toUtc(),
    final int ms => DateTime.fromMillisecondsSinceEpoch(ms, isUtc: true),
    _ => throw FormatException('Unsupported timestamp: $value'),
  };

  static int _toInt(Object? v) => switch (v) {
    null => 0,
    final int i => i,
    final num n => n.toInt(),
    final String s => int.tryParse(s) ?? 0,
    _ => 0,
  };

  @override
  bool operator ==(Object other) =>
      other is ClipItem &&
      other.id == id &&
      other.updatedAt == updatedAt &&
      other.content == content &&
      other.deletedAt == deletedAt;

  @override
  int get hashCode => Object.hash(id, updatedAt, content, deletedAt);

  @override
  String toString() =>
      'ClipItem($id, ${type.wire}, ${sizeBytes}B, from $deviceName'
      '${isDeleted ? ', deleted' : ''})';
}
