#!/usr/bin/env python3
"""Writes an SPDX 2.3 bill of materials for everything the app is built from.

    scripts/generate_sbom.py <version> <output.spdx.json>

Reads the two `pubspec.lock` files, which are the authoritative record of what
a build actually resolved, rather than the ranges `pubspec.yaml` asks for.

This exists instead of an off-the-shelf SBOM action because the repository
restricts which Actions may run, and that allowlist is worth more than the
convenience of a third-party scanner. The lock format is generated by pub and
stable, so a focused reader is enough; anything it cannot parse is reported
rather than silently dropped, since a bill of materials that quietly omits a
dependency is worse than none.
"""

from __future__ import annotations

import json
import re
import sys
import uuid
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPO = "https://github.com/appfide/nija"

# The app and the core package resolve independently, so the same dependency
# can legitimately appear at two versions. Each is recorded against the
# component that actually pulls it in.
COMPONENTS = {
    "nija": ROOT / "apps" / "nija" / "pubspec.lock",
    "nija_core": ROOT / "packages" / "nija_core" / "pubspec.lock",
}


class LockError(RuntimeError):
    """The lock file did not look the way pub writes it."""


def parse_lock(path: Path) -> dict[str, dict[str, str]]:
    """Maps package name to {version, source, url} from a pubspec.lock."""
    if not path.is_file():
        raise LockError(f"{path} is missing; run `pub get` before building an SBOM")

    packages: dict[str, dict[str, str]] = {}
    in_packages = False
    current: str | None = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        if not raw.startswith(" "):
            # A new top-level key ends the packages block.
            in_packages = raw.startswith("packages:")
            current = None
            continue
        if not in_packages:
            continue

        indent = len(raw) - len(raw.lstrip(" "))
        line = raw.strip()

        if indent == 2 and line.endswith(":"):
            current = line[:-1].strip('"')
            packages[current] = {"version": "", "source": "", "url": ""}
            continue
        if current is None:
            continue

        m = re.match(r'(version|source|url|name):\s*"?([^"]*)"?$', line)
        if m:
            key, value = m.group(1), m.group(2).strip()
            if key in ("version", "source") and not packages[current][key]:
                packages[current][key] = value
            elif key == "url" and not packages[current]["url"]:
                packages[current]["url"] = value

    if not packages:
        raise LockError(f"no packages parsed from {path}; the lock format may have changed")
    missing = [n for n, p in packages.items() if not p["version"]]
    if missing:
        raise LockError(f"no version resolved for {', '.join(sorted(missing))} in {path}")
    return packages


def component_version(lock: Path, release: str) -> str:
    """A component's own `version:`, falling back to the release version."""
    pubspec = lock.parent / "pubspec.yaml"
    if pubspec.is_file():
        m = re.search(r"^version:\s*([0-9]+\.[0-9]+\.[0-9]+)", pubspec.read_text(), re.MULTILINE)
        if m:
            return m.group(1)
    return release


def spdx_id(name: str, version: str = "") -> str:
    """SPDX identifiers allow only letters, digits, '.' and '-'."""
    raw = f"{name}-{version}" if version else name
    return "SPDXRef-Package-" + re.sub(r"[^A-Za-z0-9.-]", "-", raw)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {Path(sys.argv[0]).name} <version> <output>", file=sys.stderr)
        return 2
    version, out = sys.argv[1], Path(sys.argv[2])

    packages: list[dict[str, object]] = []
    relationships: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()

    roots = {name: spdx_id(name) for name in COMPONENTS}

    for component, lock in COMPONENTS.items():
        root_id = roots[component]
        packages.append(
            {
                "SPDXID": root_id,
                "name": component,
                "versionInfo": component_version(lock, version),
                "downloadLocation": REPO,
                "filesAnalyzed": False,
                "licenseConcluded": "MIT",
                "licenseDeclared": "MIT",
                "supplier": "Organization: Appfide",
            }
        )
        relationships.append(
            {
                "spdxElementId": "SPDXRef-DOCUMENT",
                "relationshipType": "DESCRIBES",
                "relatedSpdxElement": root_id,
            }
        )

        for name, meta in sorted(parse_lock(lock).items()):
            if name in roots:
                relationships.append(
                    {
                        "spdxElementId": root_id,
                        "relationshipType": "DEPENDS_ON",
                        "relatedSpdxElement": roots[name],
                    }
                )
                continue
            pid = spdx_id(name, meta["version"])
            host = meta["url"].rstrip("/") or "https://pub.dev"
            hosted = meta["source"] == "hosted"
            if (name, meta["version"]) not in seen:
                seen.add((name, meta["version"]))
                packages.append(
                    {
                        "SPDXID": pid,
                        "name": name,
                        "versionInfo": meta["version"],
                        "downloadLocation": (
                            f"{host}/packages/{name}/versions/{meta['version']}"
                            if hosted
                            else "NOASSERTION"
                        ),
                        "filesAnalyzed": False,
                        # Pub publishes no machine-readable licence field, and
                        # guessing one in an artifact auditors rely on is worse
                        # than admitting it is unknown.
                        "licenseConcluded": "NOASSERTION",
                        "licenseDeclared": "NOASSERTION",
                        "externalRefs": (
                            [
                                {
                                    "referenceCategory": "PACKAGE-MANAGER",
                                    "referenceType": "purl",
                                    "referenceLocator": f"pkg:pub/{name}@{meta['version']}",
                                }
                            ]
                            if hosted
                            else []
                        ),
                    }
                )
            relationships.append(
                {
                    "spdxElementId": root_id,
                    "relationshipType": "DEPENDS_ON",
                    "relatedSpdxElement": pid,
                }
            )

    doc = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": f"nija-{version}",
        "documentNamespace": f"{REPO}/sbom/{version}/{uuid.uuid4()}",
        "creationInfo": {
            "created": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "creators": ["Tool: nija-generate-sbom", "Organization: Appfide"],
        },
        "packages": packages,
        "relationships": relationships,
    }

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    deps = len(packages) - len(COMPONENTS)
    print(f"{out}: {len(packages)} packages ({deps} dependencies)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except LockError as e:
        print(f"::error::{e}", file=sys.stderr)
        raise SystemExit(1) from e
